#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [16]:
import pandas as pd
data_path = '../data/supermarket_sales.csv'
df = pd.read_csv(data_path)

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [17]:
df.groupby('Branch')['gross income'].sum()

Branch
A    5057.1605
B    5057.0320
C    5265.1765
Name: gross income, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [21]:
df.groupby('City')['gross income'].sum().sort_values(ascending = False)

City
Naypyitaw    5265.1765
Yangon       5057.1605
Mandalay     5057.0320
Name: gross income, dtype: float64

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [31]:
invoices_by_category = pd.pivot_table(df, index = 'Branch', columns  = 'Product line', values = ['Quantity'], aggfunc = 'count')
invoices_by_category

                           Quantity                                         \
Product line Electronic accessories Fashion accessories Food and beverages
Branch
A                                60                  51                 58
B                                55                  62                 50
C                                55                  65                 66


Product line Health and beauty Home and lifestyle Sports and travel
Branch
A                           47                 65                59
B                           53                 50                62
C                           52                 45                45

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [37]:
s = invoices_by_category[('Quantity', 'Electronic accessories')]

top_branch = s.sort_values(ascending=False).head(1)
top_branch

Branch
A    60
Name: (Quantity, Electronic accessories), dtype: int64

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

1. Клієнти 'Members' , які купують частіше і приносять більший середній чек та більший сумарний прибуток, але це може залежати і від категорії товарів (Product line) 

Member, Female  - Найбільше: Food and beverages (933.28)

Member, Male  - Найбільше: Health and beauty (831.03)

Normal, Female - Найбільше: Electronic accessories (759.45)

Normal, Male - Найбільше: Sports and travel (712.95)

(акції, знижки, промо-пакети відносно цих категорій)

In [39]:
p1 = pd.pivot_table(df, index = ['Customer type', 'Gender'], columns = 'Product line', values = 'gross income', aggfunc = 'sum')
p1

Product line          Electronic accessories  Fashion accessories  \
Customer type Gender
Member        Female                531.1215             720.1265
              Male                  635.4735             533.3955
Normal        Female                759.4510             729.2735
              Male                  661.4555             603.1995

Product line          Food and beverages  Health and beauty  \
Customer type Gender
Member        Female            933.2765           399.0185
              Male              559.9435           831.0310
Normal        Female            646.2910           484.8380
              Male              534.0530           627.6715

Product line          Home and lifestyle  Sports and travel
Customer type Gender
Member        Female            820.6820           793.2485
              Male              511.6050           551.2420
Normal        Female            609.6455           567.4525
              Male              622.9205           712.9535

2. У різних містах чи філіалах різні категорії дають прибуток. Потрібно, щоб прийняти рішення щодо асортименту під локацію, де розміщувати новий магазин, що завозити більше, що скоротити.

In [40]:
city_product_profit = pd.pivot_table(
    df,
    index="City",
    columns="Product line",
    values="gross income",
    aggfunc="sum"
)

city_product_profit

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
City,,,,,,
Mandalay,811.9735,781.5865,724.5185,951.460,835.6745,951.8190
Naypyitaw,903.2845,1026.6700,1131.7550,791.206,661.6930,750.5680
Yangon,872.2435,777.7385,817.2905,599.893,1067.4855,922.5095

3. Є пікові години і дні тижня за прибутком чи виручкою, і ці піки відрізняються по містах чи філіалах.
Що воно нам дає: графік персоналу, можливо промо-акціїї в “тихі” години, інше планування.

In [42]:
def get_hour(time):
    return int(time[:2])

df['Hour'] = df.Time.apply(get_hour)

In [43]:
df['Date'] = pd.to_datetime(df['Date'])
df['day_name'] = df['Date'].dt.day_name()

In [45]:
df.groupby(['day_name', 'Hour'])['gross income'].sum().sort_values(ascending=False).head(10)

day_name   Hour
Tuesday    19      438.0320
Saturday   19      434.1610
Tuesday    15      334.2955
Thursday   10      327.8680
Friday     13      324.9670
Saturday   18      320.8930
Wednesday  13      320.6830
Sunday     19      283.9830
Saturday   13      270.9350
Friday     10      270.0805
Name: gross income, dtype: float64

In [47]:
df.groupby(['day_name', 'Hour'])['gross income'].sum().sort_values(ascending=True).head(10)

day_name  Hour
Friday    17       90.1625
Monday    14       95.4450
Friday    12      102.8210
Sunday    16      106.7250
Monday    20      113.4585
Sunday    20      114.1220
Tuesday   18      115.1230
Thursday  12      122.0995
          13      123.5345
Monday    19      123.7440
Name: gross income, dtype: float64